id = "goop"
name = "Goop"
version = "0.1.1"
schema_version = 1

[grammars.goop]
path = "grammars/goop.tmLanguage.json"
title = "Goop"

[language_servers.goop]
name = "Goop Language Server"
languages = ["Goop"]

[icon_theme]
path = "icons/theme.json"
