//line ../docs/examples/concurrency.c0:1:1
// generated by c0; do not edit
package main

import (
	"fmt"
	"strconv"
)

func main() {
	ch := C0ChanMake()
	v := C0ChanRecv(ch).(int)
fmt.Println(strconv.Itoa(v))
}

// C0 file-operations‑safe channel wrapper with close‑time tracking
type C0Chan struct {
	ch     chan interface{}
	closed bool
}

func C0ChanMake() *C0Chan {
	return &C0Chan{ch: make(chan interface{})}
}

func C0ChanSend(c *C0Chan, v interface{}) {
	if c.closed { panic("Chan.send: channel is closed") }
	c.ch <- v
}

func C0ChanRecv(c *C0Chan) interface{} {
	return <-c.ch
}

func C0ChanClose(c *C0Chan) {
	if c.closed { panic("Chan.close: channel already closed") }
	c.closed = true
	close(c.ch)
}

