//line tests/fixtures/callpkg/callpkg.goop:1:1
// generated by c0; do not edit
package callpkg

import "strconv"

func Add(a int, b int) int {
	return a + b
}

func Emit_request(a int, b int, c int, d int) int {
	return a + b + c + d
}

func Zero_arg() int {
	return 42
}

func New_scope(log string, attrs int) string {
	return log + ":" + strconv.Itoa(attrs)
}

func any_of[T any](x T) interface{} { return x }

func go_slice_len[T any](xs []T) int { return len(xs) }

func go_slice_append[T any](xs []T, x T) []T { return append(xs, x) }

func go_slice_get[T any](xs []T, i int) T { return xs[i] }

func go_slice_of_list[T any](xs []T) []T { return xs }

func list_of_go_slice[T any](xs []T) []T { return xs }

