//line tests/fixtures/recpkg/recpkg.goop:1:1
// generated by c0; do not edit
package recpkg

// Option type: OptionString
type OptionTagString byte

const (
	optionTagStringNone OptionTagString = iota
	optionTagStringSome
)

type OptionString struct {
	tag  OptionTagString
	some string
}

func NewOptionStringNone() OptionString {
	return OptionString{tag: optionTagStringNone}
}

func NewOptionStringSome(v string) OptionString {
	return OptionString{tag: optionTagStringSome, some: v}
}

func (o OptionString) IsSome() bool { return o.tag == optionTagStringSome }

func (o OptionString) MustSome() string {
	if o.tag != optionTagStringSome { panic("Option.Some on None") }
	return o.some
}

func (o OptionString) SomeOr(def string) string {
	if o.tag == optionTagStringSome { return o.some }
	return def
}

type Cfg struct {
	Name string
	N int
	Label OptionString
}

func Default_cfg() Cfg {
	return Cfg{Name: "default", N: 0, Label: NewOptionStringNone()}
}

func Bump(c Cfg) Cfg {
	return Cfg{
		Name: c.Name,
		Label: c.Label,
		N: c.N + 1,
	}
}

func With_label(c Cfg, s string) Cfg {
	return Cfg{
		Name: c.Name,
		N: c.N,
		Label: NewOptionStringSome(s),
	}
}

func any_of[T any](x T) interface{} { return x }

func go_slice_len[T any](xs []T) int { return len(xs) }

func go_slice_append[T any](xs []T, x T) []T { return append(xs, x) }

func go_slice_get[T any](xs []T, i int) T { return xs[i] }

func go_slice_of_list[T any](xs []T) []T { return xs }

func list_of_go_slice[T any](xs []T) []T { return xs }

